service: circle-poc

plugins:
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

functions:
  lambdaOne:
    handler: packages/lambda-one/src/handler.hello
    memorySize: 1024
    events:
      - http:
          cors: true
          method: get
          path: /lambdaOne