service: localstack-poc

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: local
  lambdaHashingVersion: '20201221'

custom:
  localstack:
    debug: true
    stages:
     - local
     - dev
    endpointFile: localstack_endpoints.json

functions:
  lambdaOne:
    handler: packages/lambda-one/src/handler.hello
    events:
      - http:
          cors: true
          method: get
          path: /lambdaOne