version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0
  serverless: circleci/serverless-framework@1.0

defaults: &defaults
  docker:
    - image: circleci/node:14
  working_directory: ~/repo
jobs:
  load_dependencies:
    <<: *defaults
    description: "Load dependencies"
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            npm install
            npm run setup

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      - persist_to_workspace:
          root: ~/repo
          paths: .
  test:
    <<: *defaults
    description: "Run tests"
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      # run tests!
      - run: 
          name: Run tests with coverage
          command: npm run test
  publish:
    <<: *defaults
    description: "Publish on AWS w serverless"
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - serverless/setup
      - aws-cli/setup
      - run:
          name: Serverless deploy application
          command: 
            npm run deploy

workflows:
  default:
    jobs:
      - load_dependencies
      - test:
          requires:
            - load_dependencies
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - test